# Generated by Django 4.2.3 on 2023-07-31 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('WasteNotWizards', '0015_post_reserved_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='reserved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
